---
server:
  port: 8080
  contextPath: /
---
spring:
  profiles: local , default
datasource:
  paymentapp:
    url: jdbc:mysql://localhost:3306/inventory
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
---
spring:
  profiles: prod
datasource:
  paymentapp:
    url: jdbc:mysql://localhost:3306/inventory
    username: root
    password: 
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect

